robot_radius: 0.4
#footprint: [[0.35, 0.35], [-0.35, 0.35], [-0.35, -0.35], [0.35, -0.35]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 7.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 6.5

obstacles_laser:
    observation_sources: laser
    laser: 
        data_type: LaserScan
        clearing: true
        marking: true
        topic: /scan
        inf_is_valid: true
        sensor_frame: laser




