global_frame: odom
rolling_window: true
track_unknown_space: false


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}


obstacles_laser:
   update_frequency: 7.0
   publish_frequency: 3.0

inflation:
    inflation_radius: 1.2