global_frame: odom
rolling_window: false
track_unknown_space: false



plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}


inflation:
    inscribed_radius: 1.0
    circumscribed_radius: 1.2
    inflation_radius: 1.5
