global_frame: map
rolling_window: false
track_unknown_space: false



plugins:
  - {name: static_layer,              type: "costmap_2d::StaticLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

static_layer:
    map_topic: "/map"
    track_unknown_space: false
    subscribe_to_updates: true


inflation:
    inflation_radius: 1.5